source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

inhibit_all_warnings!

def common_pods
    pod 'RxCocoa', '~> 4.2' 
end

target :MVVM do
    common_pods
end

target :MVVMTests do
    common_pods
    pod 'RxTest', '~> 4.2'
end